refinery29/php-cs-fixer-config

- src/Refinery29.php
- tests/Refinery29Test.php
This PR
See https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage:
> **unused_use [symfony]**
> Unused use statements must be removed.
> Enhancement: Enable unused_use fixer

- src/Refinery29.php
- tests/Refinery29Test.php
This PR
See https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage:
> **unalign_equals** [symfony]
>Unalign equals symbols.
> Enhancement: Enable unalign_equals fixer

- src/Refinery29.php
- tests/Refinery29Test.php
This PR
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master#usage:
> **method_separation [symfony]**
> Methods must be separated with one blank line.
> Enhancement: Enable method_separation fixer

- .travis.yml
- composer.json
- composer.lock
- tests/Refinery29Test.php
> Enhancement: Only require PHP5.4 and above

- .travis.yml
- bin/report-coverage
- composer.json
- composer.lock
> Fix: Require codeclimate/php-test-reporter:0.2.0

- src/Refinery29.php
- test/Refinery29Test.php
This PR
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master#usage:
> `phpdoc_types`
The correct case must be used for standard PHP types in phpdoc.
> Enhancement: Enable phpdoc_types fixer

- .travis.yml
- composer.json
- composer.lock
- test/Refinery29Test.php
> Fix: Drop PHP5.4

- src/Refinery29.php
- test/Refinery29Test.php
This PR
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master#usage:
> `array_element_no_space_before_comma [@Symfony]`
In array declaration, there MUST NOT be a whitespace before each comma.
> Enhancement: Enable array_element_no_space_before_comma fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master#usage:
> `array_element_white_space_after_comma [@Symfony]`
In array declaration, there MUST be a whitespace after each comma.
> Enhancement: Enable array_element_white_space_after_comma fixer

- composer.json
- composer.lock
> Fix: Require fabpot/php-cs-fixer using the branch alias

- composer.lock
- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **unneeded_control_parentheses [symfony]**
Removes unneeded parentheses around control statements.
> Enhancement: Enable unneeded_control_parentheses fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **spaces_after_semicolon** [symfony]
Fix whitespace after a semicolon.
> Enhancement: Enable spaces_after_semicolon fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **short_bool_cast** [symfony]
Short cast bool using double exclamation mark should not be used.
> Enhancement: Enable short_bool_cast fixer

- README.md
- src/Refinery29.php
- test/Refinery29Test.php
> Enhancement: Allow to specify a header comment

- README.md
> Fix: Use branch alias in README

- Makefile
> Fix: Make it first target

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **unary_operators_spaces** [@Symfony]
Unary operators should be placed adjacent to their operands.
> Enhancement: Enable unary_operators_spaces fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **short_scalar_cast** [@Symfony]
Cast "(boolean)" and "(integer)" should be written as "(bool)" and "(int)". "(double)" and "(real)" as "(float)".
> Enhancement: Enable short_scalar_cast fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **pre_increment** [@Symfony]
Pre incrementation/decrementation should be used if possible.
> Enhancement: Enable pre_increment fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **native_function_casing** [`@Symfony`]
Function defined by PHP should be called using the correct casing.
> Enhancement: Enable native_function_casing fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **hash_to_slash_comment** [`@Symfony`]
Single line comments should use double slashes (//) and not hash (#).
> Enhancement: Enable hash_to_slash_comment fixer

- Makefile
> Fix: Revert changes to Makefile

- composer.json
- composer.lock
This PR
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/2ac4bdb4cb989d7b32821265ef6dcdf9dcda06ba.
/cc @rcatlin
> Fix: Require a working commit of fabpot/php-cs-fixer

- src/Refinery29.php
- test/Refinery29Test.php
> Fix: Disable phpdoc_summary fixer

- src/Refinery29.php
- test/Refinery29Test.php
> Fix: Disable no_unreachable_default_argument_value fixer

- README.md
> Fix: Add note about unstable dependency

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **no_unreachable_default_argument_value** [`@Symfony`]
In method arguments there must not be arguments with default values before non-default ones.
> Enhancement: Enable no_unreachable_default_argument_value fixer

- composer.json
- composer.lock
- src/Refinery29.php
- test/Refinery29Test.php
This PR
:information_desk_person: This effectively enables the `no_trailing_whitespace_in_comment` fixer as it has been moved from the Symfony to the PSR2 level.
> **no_trailing_whitespace_in_comment** [`@PSR2`, `@Symfony`]
> There MUST be no trailing spaces inside comments and phpdocs.
For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/518194b...0a63dfb.
> Fix: Update fabpot/php-cs-fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **no_useless_return**
There should not be an empty return statement at the end of a function.
> Enhancement: Enable no_useless_return fixer

- composer.json
- composer.lock
This PR
Follows https://github.com/refinery29/php-cs-fixer-config/pull/60.
> Fix: Require fabpot/php-cs-fixer as actual dependency

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **combine_consecutive_unsets**
>Calling unset on multiple items should be done in one call.
> Fix: Enable combine_consecutive_unsets fixer

- test/Refinery29Test.php
> Fix: Fixer is contrib level

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **phpdoc_single_line_var_spacing [`@Symfony`]**
>Single line `@var` PHPDoc should have proper spacing.
> Enhancement: Enable phpdoc_single_line_var_spacing fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
>**no_empty_comment**
>There should not be an empty comments.
> Enhancement: Enable no_empty_comment fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
Follows #76.
> **no_empty_statement** [`@Symfony`]
> Remove useless semicolon statements.
> Enhancement: Enable no_empty_statement fixer

- test/Refinery29Test.php
> Fix: Reduce visibility

- src/Refinery29.php
- test/Refinery29Test.php
This PR
Follows #82.
Follows https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1861.
> **no_spaces_inside_offset** [`@Symfony`]
> There MUST NOT be spaces between the offset square braces and its contained values.
> Enhancement: Enable no_spaces_inside_offset fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
Follows #89.
>`no_useless_else`
>There should not be useless else cases.
> Enhancement: Enable no_useless_else fixer

- README.md
- composer.json
- composer.lock
This PR
Follows https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1875.
> Fix: Package fabpot/php-cs-fixer renamed to friendsofphp/php-cs-fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
💁 For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master#usage.
>**phpdoc_summary** [`@Symfony`]
>Phpdocs summary should end in either a full stop, exclamation mark, or question mark.
> Fix: Enable phpdoc_summary fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> `modernize_types_casting`
> Replaces `intval`, `floatval`, `doubleval`, `strval`, `boolval` functions calls with according type casting operator. (Risky fixer!)
> Enhancement: Enable modernize_types_casting fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> `no_multiline_whitespace_before_semicolons`
> Multi-line whitespace before closing semicolon are prohibited.
> Enhancement: Enable no_multiline_whitespace_before_semicolons fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> `binary_operator_spaces` [`@Symfony`]
> Binary operators should be surrounded by at least one space.
For examples, see [`BinaryOperatorSpacesFixerTest`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php).
> Enhancement: Enable binary_operator_spaces fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> `no_empty_phpdoc` [`@Symfony`]
> There should not be empty PHPDoc blocks.
> Enhancement: Enable no_empty_phpdoc fixer

- src/Refinery29.php
This PR
💁‍♂️ This is to prepare for updating to [`friendsofphp-php-cs-fixer:2.0.0-RC`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.0.0-RC). The reason is that rules have been moved from different rule sets to others, and in the end, we don't care much about to which ruleset they belong (that is, other than `@PSR2`, because we use this as a base), as long as the fixers are enabled.
> Fix: Return rules from a single method

- test/Refinery29Test.php
> Fix: Actually remove method

- src/Refinery29.php
- test/Refinery29Test.php
> Fix: Cache is used by default

- src/Refinery29.php
- test/Refinery29Test.php
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master#usage:
> `normalize_index_brace [@Symfony]`
> Array index should always be written by using square braces.
> Enhancement: Enable normalize_index_brace fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/README.rst#usage:
> `php_unit_fqcn_annotation [@Symfony]`
> PHPUnit @expectedException annotation should be a FQCN including a root
namespace.
> Enhancement: Enable php_unit_fcqn_annotation fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master#usage:
> `return_type_declaration [@Symfony]`
> There should be no space before colon and one space after it in return
type declaration.
> Enhancement: Enable return_type_declaration fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master#usage:
> `semicolon_after_instruction`
> Instructions must be terminated with a semicolon.
> Enhancement: Enable semicolon_after_instruction fixer

- .travis.yml
This PR
Blocks #130.
💁‍♂️ The idea is this: `php-cs-fixer` itself only applies fixers targeted at PHP 7 when the version it is run in is PHP 7. If we let it run on a version below that, `refinery29/php-cs-fixer-config` can be compatible to that version. PHP 7 features aren't really required for `refinery29/php-cs-fixer-config`, but we want to enable fixers for code that runs on PHP 7 only.
> Fix: Run php-cs-fixer on PHP 5.6 on Travis

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **declare_strict_types**
> Force strict types declaration in all files. Requires PHP >= 7.0.
> Rule is: risky.
> Enhancement: Enable declare_strict fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **declare_equal_normalize [`@Symfony`]**
Equal sign in declare statement should not be surrounded by spaces.
> Enhancement: Enable declare_equal_normalize fixer

- composer.json
- composer.lock
This PR
Follows #125.
💁‍♂️ There really is no need to use an exact version constraint, now that we have a stable version.
> Fix: No need to pin friendsofphp/php-cs-fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> **no_mixed_echo_print** `[@Symfony]`
Either language construct print or echo should be used.
Rule is: configurable.
> Enhancement: Enable no_mixed_echo_print fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> `phpdoc_add_missing_param_annotation`
Phpdoc should contain `@param` for all params.
Rule is: configurable.
> Enhancement: Enable phpdoc_add_missing_param_annotation fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> `protected_to_private`
Converts protected variables and methods to private where possible.
> Enhancement: Enable protected_to_private fixer

- composer.json
- composer.lock
This PR
💁‍♂️ For reference, see https://getcomposer.org/doc/06-config.md#sort-packages.
> Fix: Keep packages sorted

- README.md
This PR
```
[Symfony\Component\Console\Exception\RuntimeException]
The "--config-file" option does not exist.
```
> Fix Readme, --config instead of --config-file

- test/Refinery29Test.php
This PR
Follows https://github.com/refinery29/test-util/pull/126.
💁‍♂️ For reference, see 
* https://twitter.com/Ocramius/status/811504929357660160
* http://php.net/manual/en/language.namespaces.faq.php#language.namespaces.faq.shortname2
* http://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/
>Function or constant names that do not contain a backslash like name can be resolved in 2 different ways.
>
>First, the current namespace name is prepended to _name_.
>
>Finally, if the constant or function _name_ does not exist in the current namespace, a global constant or function _name_ is used if it exists.
> Fix: Remove need to resolve global function in current namespace

- test/Refinery29Test.php
> Fix: Do not use reflection to determine fixers by name

- src/Refinery29.php
- test/Refinery29Test.php
This PR
💁‍♂️ By popular request, when using PHP7, using this fixer is risky.
> Fix: Disable simplified_null_return fixer

- .travis.yml
- composer.json
- composer.lock
- src/Refinery29.php
- test/Refinery29Test.php
> Fix: Drop support for PHP 5.6

- src/Refinery29.php
- test/ProjectCodeTest.php
- test/Refinery29Test.php
> Fix: Mark production and test code as final

- .travis.yml
- composer.json
> Fix: Drop support for PHP 7.0

- src/Refinery29.php
- test/Refinery29Test.php
> Enhancement: Configure visibility_required fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
Master is probably not the best branch to merge this since it requires php7. Anyway just to explain the reason behind this change.
If you want to add arbitrary comment somewhere in the code where you want to put `@see` annotation to give more context to the code, something like this
```php
/**
* @see Controller::action()
*/
```
fixer will transform it to regular comment starting with `/*` which prevents PHPStorm from understanding that it really is a Docblock and you're not able to click on it to open the file.
> Fix: Disable phpdoc_to_comment fixer

- test/Refinery29Test.php
> Fix: Add note about why phpdoc_to_comment fixer is disabled

- .github/CONTRIBUTING.md
> Fix: Package has been renamed

- composer.json
This PR
Follows #168.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v2.0.0...v2.0.1.
> Fix: Update friendsofphp/php-cs-fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> `is_null [@Symfony:risky]`
>Replaces `is_null(parameter)` expression with `null === parameter`.
> Rule is: configurable, risky.
> Enhancement: Enable is_null fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
>`native_function_invocation`
>Add leading `\` before function invocation of internal function to speed
>up resolving.
>Rule is: configurable, risky.
> Enhancement: Enable native_function_invocation fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> `phpdoc_no_useless_inheritdoc [@Symfony]`
> Classy that does not inherit must not have inheritdoc tags.
> Enhancement: Enable phpdoc_no_useless_inheritdoc fixer

- src/Refinery29.php
- test/Refinery29Test.php
This PR
> `phpdoc_return_self_reference [@Symfony]`
>The type of `@return` annotations of methods returning a reference to
>itself must the configured one.
>Rule is: configurable.
> Enhancement: Enable phpdoc_return_self_reference fixer

- README.md
This PR
💁‍♂️ It still references an old version of `friendsofphp/php-cs-fixer`.
> Fix: Update git pre-commit hook example

- .php_cs
- src/Php71.php
- test/Php71Test.php
> Fix: Rename Refinery29 to Php71

- README.md
- src/Php70.php
- test/Php70Test.php
> Enhancement: Pick Refinery29 from 0.7 as Php70

- README.md
- src/Php56.php
- test/Php56Test.php
> Enhancement: Pick Refinery29 from 0.6 as Php56

- .php_cs
- .travis.yml
- composer.json
- src/Php56.php
- src/Php70.php
- src/Php71.php
- test/Php56Test.php
- test/Php70Test.php
- test/Php71Test.php
- test/ProjectCodeTest.php
> Fix: Lower PHP version constraints

- Makefile
> Fix: Remove composer.lock in composer target

- src/Php56.php
This PR
💁‍♂️ While yoda-style conditions are great, this is hard on legacy projects. We can still go back and re-enable it for all configurations.
> Fix: Do not use yoda style conditions with is_null fixer

- test/AbstractConfigTestCase.php
- test/Php56Test.php
- test/Php70Test.php
- test/Php71Test.php
This PR
Follows #181.
Follows #182.
Follows #183.
> Fix: Extract AbstractConfigTestCase

- src/Php56.php
- src/Php70.php
- src/Php71.php
- test/Php56Test.php
- test/Php70Test.php
- test/Php71Test.php
This PR
>**doctrine_annotation_indentation**
>
>Doctrine annotations must be indented with four spaces.
> Enhancement: Enable doctrine_annotation_indentation fixer

- src/Php56.php
- src/Php70.php
- src/Php71.php
- test/Php56Test.php
- test/Php70Test.php
- test/Php71Test.php
This PR
>**doctrine_annotation_spaces**
>
>Fixes spaces in Doctrine annotations.
> Enhancement: Enable doctrine_annotation_spaces fixer

- src/Php56.php
- src/Php70.php
- src/Php71.php
- test/Php56Test.php
- test/Php70Test.php
- test/Php71Test.php
This PR
>**function_to_constant** [`@Symfony:risky`]
>
>Replace core functions calls returning constants with the constants.
>
>*Risky rule: risky when any of the configured functions to replace are overridden.*
> Enhancement: Enable function_to_constant fixer

- src/Php56.php
- src/Php70.php
- src/Php71.php
- test/Php56Test.php
- test/Php70Test.php
- test/Php71Test.php
This PR
>magic_constant_casing [`@Symfony`]
>
>Magic constants should be referred to using the correct casing.
> Enhancement: Enable magic_constant_casing fixer

- src/Php56.php
- src/Php70.php
- src/Php71.php
- test/Php56Test.php
- test/Php70Test.php
- test/Php71Test.php
This PR
>**non_printable_character** [`@Symfony:risky`]
>
>Remove Zero-width space (ZWSP), Non-breaking space (NBSP) and other invisible unicode symbols.
>
>Risky rule: risky when strings contain intended invisible characters.
> Enhancement: Enable non_printable_character fixer

- src/Php71.php
- test/Php71Test.php
This PR
Follows #200.
>list_syntax
>
>List (`array` destructuring) assignment should be declared using the configured syntax. Requires PHP >>= 7.1.
>
>Configuration options:
>
>`syntax` (`'long'`, `'short'`): whether to use the `long` or `short` `list` syntax; defaults to `'long'`
> Enhancement: Enable list_syntax fixer

- phpunit.xml
This PR
💁‍♂️ This way it will always link to the appropriate schema, regardless of which version is installed, and doesn't need any updates. For reference, also see https://github.com/sebastianbergmann/phpunit/blob/master/phpunit.xsd.
> Fix: Use relative path for phpunit.xsd instead of absolute, remote path
