README.md
=> Enhancement: Add note about pre-commit hook

composer.json, composer.lock, src/Refinery29.php, tests/Refinery29Test.php
=> Enhancement: Update to latest rules feature

src/Refinery29.php, tests/Refinery29Test.php
=> Enhancement: Enable newline_after_open_tag fixer

src/Refinery29.php, tests/Refinery29Test.php
=> Fix: Disable PSR-0 fixer

composer.json, composer.lock
=> Fix: Require a known commit of fabpot/php-cs-fixer

composer.json, composer.lock
This PR
:information_desk_person: See https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/59ed377...7b12997.
=> Enhancement: Update fabpot/php-cs-fixer

Makefile
=> Enhancement: Add it target

.travis.yml
=> Fix: Disable Travis email notifications

.php_cs, src/Refinery29.php, test/Refinery29Test.php
=> Fix: Add file level headers

composer.lock
=> Fix: Update fabpot/php-cs-fixer

composer.lock, src/Refinery29.php
This PR
For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/10451b837f92f331acecafa69e00a4a6e9a6152d...6c20503c00b6c3466ffff21a9b4003636cd77de4.
=> Fix: Update fabpot/php-cs-fixer-config

README.md
=> Fix: Update README.md to reflect .travis.yml

README.md
=> Fix: Commit reference in README.md

composer.json, composer.lock
=> Fix: Allow to install on PHP7

.gitattributes, .github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
=> Enhancement: Leverage GitHub template capabilities

.travis.yml
=> Fix: Run build on PHP7

src/Refinery29.php
=> Fix: Reduce visibility of method

test/Refinery29Test.php
=> Fix: Merge tests

README.md
This PR fixes a wee and misleading documentation error.
=> Fix: Document correct cache directory

test/Refinery29Test.php
=> Fix: Also merge test methods

.travis.yml
=> Enhancement: Also run build on PHP 7.1

test/Refinery29Test.php
=> Fix: Inline assertion

test/Refinery29Test.php
=> Fix: Remove duplicate key

test/Refinery29Test.php
=> Fix: Simplify assertion

README.md
=> Fix: Update git hook installation notes

src/Refinery29.php, test/Refinery29Test.php
=> Fix: Keep rules sorted

test/Refinery29Test.php
=> Fix: Improve testing that we have rules for all built-in fixers

test/Refinery29Test.php
=> Fix: Simplify test

.travis.yml, composer.json, composer.lock, src/Refinery29.php, test/Refinery29Test.php
This PR
💁‍♂️ Issued against the wrong branch!
=> Fix: Restore support for PHP 5.6

.travis.yml, composer.json, composer.lock
=> Fix: Drop support for PHP5.5

composer.json, composer.lock
This PR
💁‍♂️ For reference, see https://github.com/codeclimate/php-test-reporter/compare/v0.3.2...v0.4.0.
=> Enhancement: Update codeclimate/php-test-reporter

composer.json, composer.lock, phpunit.xml
This PR
💁‍♂️ For reference, see https://github.com/sebastianbergmann/phpunit/compare/4.8.28...5.7.5.
=> Enhancement: Update phpunit/phpunit

composer.json, composer.lock
=> Enhancement: Require refinery29/test-util

.github/CONTRIBUTING.md
=> Fix: Styles in CONTRIBUTING.md

.travis.yml
=> Fix: Run php-cs-fixer on all PHP versions

composer.json
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v2.0.0...v2.0.1.
=> Fix: Update friendsofphp/php-cs-fixer

composer.json
This PR
💁‍♂️ For reference, see https://github.com/codeclimate/php-test-reporter/compare/v0.4.2...v0.4.4.
=> Fix: Update codeclimate/php-test-reporter

composer.json
This PR
💁‍♂️ For reference, see https://github.com/sebastianbergmann/phpunit/compare/5.7.5...5.7.19.
=> Fix: Update phpunit/phpunit

composer.json
This PR
💁‍♂️ For reference, see https://github.com/refinery29/test-util/compare/0.10.2...0.11.2.
=> Enhancement: Update refinery29/test-util

src/Php56.php, src/Php70.php, src/Php71.php, test/Php56Test.php, test/Php70Test.php, test/Php71Test.php, test/ProjectCodeTest.php
=> Fix: Remove extra empty lines

README.md, composer.json
=> Fix: Update README.md

composer.json, src/Php56.php, src/Php70.php, src/Php71.php, test/Php56Test.php, test/Php70Test.php, test/Php71Test.php
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v2.2.0...v2.3.0.
=> Enhancement: Update friendsofphp/php-cs-fixer

.editorconfig, .gitattributes
This PR
💁‍♂️ For reference, see http://editorconfig.org.
=> Enhancement: Add .editorconfig
